---
- name: Install consul from "{{ consul_binary_linux }}"
  unarchive:
   src: "{{ consul_binary_linux }}"
   dest: /usr/local/bin
   remote_src: True

- name: Create /var/consul Directory
  file: path={{ datadir }} state=directory owner=consul group=consul mode=0775 recurse=yes

- name: Create /etc/consul.d Directory
  file: path={{ configdir }} state=directory owner=consul group=consul mode=0775 recurse=yes

- name: Create "{{ pluginsdir }}" Directory
  file: path={{ pluginsdir }} state=directory owner=consul group=consul mode=0775 recurse=yes

- name: copy python plugins
  copy:
    src: "{{ item }}"
    dest: "{{ pluginsdir }}"
    owner: consul
    mode: 0775
  with_fileglob:
    - "{{ role_path }}/files/plugins_python/*"

- name: Copying Json Config File for bootstrap "{{ bootstrap }}"
  template: src=nodes_conf/bootstrap.j2 dest={{ configdir }}/config.json
  when: inventory_hostname in groups.consul_Bootstrap

- name: Copying check Config Files
  template: src=nodes_conf/check_config.j2 dest={{ configdir }}/check_config.json

- name: Copying Json Config File for Servers
  template: src=nodes_conf/server.j2 dest={{ configdir }}/config.json
  when: inventory_hostname in groups.consul_Servers

- name: Copying Json Config File for clients
  template: src=nodes_conf/client.j2 dest={{ configdir }}/config.json
  when: inventory_hostname in groups.consul_Clients

- name: Copying upstart config files for Clients
  template: src=upstart_scripts/consul_client.j2 dest={{ initdir }}/consul.conf
  when: inventory_hostname in groups.consul_Clients

- name: Copying upstart config files for bootstrap
  template: src=upstart_scripts/consul_server.j2 dest={{ initdir }}/consul.conf
  when: inventory_hostname in groups.consul_Bootstrap

- name: Copying upstart config files for Servers
  template: src=upstart_scripts/consul_server.j2 dest={{ initdir }}/consul.conf
  when: inventory_hostname in groups.consul_Servers

- name: Stoping Consul if started
  command: stop consul
  register: service_consul_status
  failed_when: service_consul_status.rc != 0
  ignore_errors: true

- name: Startup consul server on bootstraping
  command: start consul
  when:
   - inventory_hostname in groups.consul_Bootstrap

- name: Startup consul servers
  command: start consul
  when:
   - inventory_hostname in groups.consul_Servers

- name: Startup consul clients
  command: start consul
  when:
   - inventory_hostname in groups.consul_Clients

- name: Copying Json Config File for bootstrap
  template: src=nodes_conf/server.j2 dest={{ configdir }}/config.json
  when: inventory_hostname in groups.consul_Bootstrap

- name: stop consul server bootstrap
  command: stop consul
  when:
    - inventory_hostname in groups.consul_Bootstrap

- name: start consul server bootstrap on normal mode
  command: start consul
  when:
    - inventory_hostname in groups.consul_Bootstrap
